# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Rafa Physics/Maths"

# A description of your site for meta tag, search engine results.
#description: "Notes in selected subjects of physics and mathematics."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""
relativeurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://scriptor-jekyll.netlify.com"

# Favicon
#favicon:""

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Index
    url: /index.html
  - text: Notes
    url: /notes.html
  - text: Projects
    url: /projects.html
  - text: Numerics
    url: /numerics.html
  #- text: Tags
  #  url: /tags.html
  #- text: Home 
  #  url: https://rafaphysics.herokuapp.com/
  - text: Personal
    url: /personal.html

# The shortname for your Disqus site to enable comments.
disqus: rafa-physis

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Scriptor all rights reserved. Theme by JustGoodThemes[](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-latex-pdf

pdf:
  pdf_engine: pdflatex
  author: Rafael C.
  template: jekyll-latex-pdf.latex 
  preamble:
    - \usepackage{amsthm}

jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      layout: post
      description: 
      tags: 
      pdf: true

    posts:
      layout: post
      description: 
      tags: 
      pdf: true

# http://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: '/page:num/'



# Permalinks
permalink: /:title

# Conversion
# Use kramdown as the Markdown processor
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
